### PR TITLE
kiab 0.7.3

### PR DESCRIPTION
**Pull request by sergiohinojosa**
Point to KIAB 0.7.3 release and update control flags table with self hosted git functionality (gitea).

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
Thanks @sergiohinojosa for the PR - looks good.
Only thing: you need to sign your commit to comply with the DCO. Learn how to do this: https://github.com/keptn/tutorials/pull/100/checks?check_run_id=1424490423 
(if you need help please reach out)

**Comment by sergiohinojosa** [comment]
I hope it's ok now, if not I would need a bit of help with this DCO.

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Comment by jetzlstorfer** [comment]
Thanks @sergiohinojosa ! It's merged now and will be live within minutes.

**Pull request merged**
