### PR TITLE
Improve dynatrace oneagent setup

### PR DESCRIPTION
**Pull request by christian-kreuzberger-dtx**
Together with @laneli we noticed that the Dynatrace OneAgent installation instructions are outdated and that the note regarding "Enable Volume storage" needs to be more prominent.

This PR fixes those instructions for Keptn 0.8.x.

Preview: https://deploy-preview-156--keptn-tutorials.netlify.app/tutorials/keptn-full-tour-dynatrace-08/index.html?index=..%2F..keptn08x#9 (Step 10)

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
Hi @christian-kreuzberger-dtx ! Thanks for the PR.
Please generate the impacted tutorials with `./builder name-of-tutorial.md` to generate the new tutorials. Updating the snippet only does not update them, unfortunately. 

You should then be able to verify via this URL https://deploy-preview-156--keptn-tutorials.netlify.app/tutorials/keptn-full-tour-dynatrace-08/index.html?index=..%2F..index#9

**Comment by christian-kreuzberger-dtx** [comment]
Done, this has added a new file called `site/tutorials/keptn-full-tour-dynatrace-08/codelab.json`  - did I do something wrong?

**Comment by jetzlstorfer** [comment]
looks good - thanks Christian! 
actually it was already fine with your first commit but I overlooked it.

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Pull request merged**
