### PR TITLE
Kiab 0.7.2

### PR DESCRIPTION
**Pull request by sergiohinojosa**
Update pointinng to KIAB release 0.7.2

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
Thanks for the PR @sergiohinojosa !
Could you please remove the generated HTML files as they are not needed anymore. When publishing the tutorial they will be automatically generated. You can keep the codelab.json files though

**Review by jetzlstorfer — CHANGES_REQUESTED** [review]
please see comment above

**Comment by sergiohinojosa** [comment]
Hi @jetzlstorfer, ok, so only the *.md file(s) right? no generated images nor html right nor codelab.json files?

**Comment by jetzlstorfer** [comment]
*.md files and the img/ folder should be removed. they should be already excluded based on the `.gitignore` file, maybe you had an older version of it and checked them in.

please keep the `codelab.json` as it has some metainformation in it that we need (mostly the timestamp).

**Comment by sergiohinojosa** [comment]
not needed, jumping to  0.7.3 directly

**Pull request closed without merging**
