### PR TITLE
#118 Updated istio version from 1.6.14 to 1.8.2 in installation guide

### PR DESCRIPTION
**Pull request by TannerGabriel**
`Istio 1.6.14` has reached its "End of Life" and therefore needs to be replaced with a newer version.

## Fixes Issue
#118

### CODE REVIEW

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Comment by jetzlstorfer** [comment]
@christian-kreuzberger-dtx could you please take a look as well?

**Review by christian-kreuzberger-dtx — APPROVED** [review]
Looks good to me too!

This can be merged. Also, can you please do the same change within PR https://github.com/keptn/tutorials/pull/112 in snippets/08/install/istio.md?

**Comment by TannerGabriel** [comment]
> Looks good to me too!
> 
> This can be merged. Also, can you please do the same change within PR #112 in snippets/08/install/istio.md?

Yes, I will do that later today.

**Pull request merged**
