### PR TITLE
spelling: inform

### PR DESCRIPTION
**Pull request by jsoref**
@jetzlstorfer this is a sample PR

### CODE REVIEW

**Comment by jsoref** [comment]
Note: my repository didn't have actions enabled which is why my commit didn't come w/ a comment.

> Quote this line to have @check-spelling-bot apply these [changes](https://api.github.com/repos/keptn/tutorials/issues/comments/814569514).

`pull_request_target` didn't happen for your branch because it only applies to the base, and the base (`master`) doesn't yet have the workflow/event.

Obviously you wouldn't want to merge this PR.

**Comment by jsoref** [comment]
Hmm, why didn't it run?

> Quote this line to have @check-spelling-bot apply these [changes](https://api.github.com/repos/keptn/tutorials/issues/comments/814569514).

**Comment by jsoref** [comment]
Oh, right, the comment handler only runs for the default branch (`master`), and #141 isn't merged, so that isn't available yet.

You can see what it would look like here:
https://github.com/check-spelling/keptn-tutorials/pull/1#issuecomment-814568392

**Comment by johannes-b** [comment]
Since this is a sample PR, I closed it.

**Pull request closed without merging**
