### PR TITLE
#9 Changed carts:0.10 to carts:0.11

### PR DESCRIPTION
**Pull request by johannes-b**
This PR updates carts from 0.10 to 0.11.

### CODE REVIEW

**Comment by johannes-b** [comment]
@jetzlstorfer: I changed the files in the snippet folder and two files directly in the tutorials folder. Can you generate the *_gen files, please?

**Comment by jetzlstorfer** [comment]
thanks for the update - I'll take a look and generate the updated versions

**Comment by jetzlstorfer** [comment]
If you want to give it a try yourself, follow this guide: https://github.com/keptn/tutorials/tree/master/site/tutorials#generate-contents-and-test-locally

**Comment by johannes-b** [comment]
Thanks for the hint. Let me try to build it on my own.

**Comment by johannes-b** [comment]
I installed claat on my local machine and then executed the script: `./builder.sh` in the tutorials folder. 

But the script runs in an error: 
```
./builder.sh: line 12: ./markymark: cannot execute binary file: Exec format error
```

`markymark` is a binary you developed. Does it work on the *Ubuntu subsystem for Windows*?

**Comment by jetzlstorfer** [comment]
The current version is for mac os. 
However, find the binary for your OS here https://github.com/jetzlstorfer/markymark/tree/master/bin

**Pull request merged**
