### PR TITLE
Update of Prometheus-service version and Examples version for Keptn 0.10

### PR DESCRIPTION
**Pull request by johannes-b**
Signed-off-by: Johannes <johannes.braeuer@dynatrace.com>

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1. I have not tested this tutorial yet and I'm not sure whether it addresses all issues

**Comment by braghettos** [comment]
@johannes-b I was looking at your commits but I cannot find the `git clone --branch 0.10.0 https://github.com/keptn/examples.git --single-branch`. Am I missing something?

**Comment by christian-kreuzberger-dtx** [comment]
@braghettos this works fine for me:
image

what's the error message you are getting?

**Comment by braghettos** [comment]
You are right @christian-kreuzberger-dtx , I was looking in the GitHub UI for the branch 0.10.0 and I couldn't find it! The command works as expected.

**Comment by christian-kreuzberger-dtx** [comment]
There is another issue in the tutorial:
```
kubectl port-forward svc/prometheus-service -n monitoring 8080:8080
```

should be
```
kubectl port-forward svc/prometheus-server 8080:80 -n monitoring
```

**Comment by christian-kreuzberger-dtx** [comment]
I fixed the port-forward and merged master branch into this branch.


@oleg-nenashev could you please review my changes?

**Review by oleg-nenashev — APPROVED** [review]
Looks good to me, thank you! I will merge it, because it's definitely an improvement compared to the previous version that was obsolete.

**Pull request merged**
