### PR TITLE
fixed misspelling in link description

### PR DESCRIPTION
**Pull request by adriangonciarz**
changed `docuemtation` to `documentation`

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
Thanks @adriangonciarz for fixing the typo!
Could you please sign your commit and we are happy to merge it 👍 
https://github.com/keptn/tutorials/pull/107/checks?check_run_id=1509312378

**Comment by adriangonciarz** [comment]
@jetzlstorfer done

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Comment by jetzlstorfer** [comment]
Thanks @adriangonciarz for your contribution!

**Pull request merged**
