### PR TITLE
Azure DevOps Tutorial Using Keptn Extension

### PR DESCRIPTION
**Pull request by heydenb**
Updated the Azure DevOps tutorial by using the extension.
Followed the same flow as the 06 version of Juergen. I am still refering to Juergen's repo for the sli, slo and runTests.sh files.

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
Thanks @heydenb for this improvement. I'll take a look and will be happy to merge it

**Comment by jetzlstorfer** [comment]
I just saw that a couple of issues in https://github.com/keptn-sandbox/keptn-azure-devops-extension/issues have been closed as well. If they are related to this PR, please mention them so we have full transparency :)

**Comment by jetzlstorfer** [comment]
sorry @heydenb for the delay. 
When reviewing the tutorial, seems that there is something missing in Step 10 - where is the demo application coming from?

image


I couldn't find any repo that has been pulled or cloned that is used at this step.

**Review by jetzlstorfer — CHANGES_REQUESTED** [review]
some issues have to be addressed. following up in comment section on this

**Comment by jetzlstorfer** [comment]
Hi @heydenb ! Did you already have the chance to take a look at this?

**Comment by jetzlstorfer** [comment]
Please consider migrating this to 0.8.x directly

**Comment by jetzlstorfer** [comment]
Hi @heydenb ! Should we close this one as it has been open for quite some time now?
I'd suggest to migrate this tutorial for Keptn 0.8.x and then open a new PR.

**Comment by heydenb** [comment]
Sure thing.

Op wo 19 mei 2021 09:36 schreef Jürgen Etzlstorfer ***@***.***

**Comment by christian-kreuzberger-dtx** [comment]
I'll take this PR into my hands, might re-create it

**Comment by oleg-nenashev** [comment]
Just in case, is it still on your list @christian-kreuzberger-dtx ?

**Comment by christian-kreuzberger-dtx** [comment]
Hi @oleg-nenashev , as of right now, this PR is not in a state where I would merge it. In addition, it targets a very old Keptn version, and writing a new tutorial targeted for Keptn 0.11/0.12/0.13 would consume too much time.

I believe we should close this PR.

**Comment by oleg-nenashev** [comment]
Will close based on the feedback. Happy to revise it for the new Keptn version

**Pull request closed without merging**
