### PR TITLE
upgrade to kiab 07

### PR DESCRIPTION
**Pull request by sergiohinojosa**
Upgrade to Keptn in a Box (KIAB) 07.

### CODE REVIEW

**Comment by sergiohinojosa** [comment]
Adding teaser image for Autonomous Cloud enablement with Keptn in a Box

**Comment by sergiohinojosa** [comment]
Matching Jenkins pwd to Unleash. Adding consistency

**Comment by sergiohinojosa** [comment]
Hi @jetzlstorfer,

yes, its a good idea to mark the releases with tags/branches. I have already some tags in the repo but it would be cleaner and better to create a branch for each release.

So:
- I'll add branches for the different versions.
- Remove the chmod step and make sure the file is executable 

For your understanding, you need to download the  `keptn-in-a-box.sh` file. **Optionally** edit the file to add the installationBundle and the features for your needs but it can be executed without editing it. This file then downloads the `functions.sh` file and the repo. So the functions.sh file and the repository with it's resources need to be on a specific branch so all the pieces work as desired for the different branches/releases.

**Comment by sergiohinojosa** [comment]
Hi @jetzlstorfer , 

changes have been commited and tested in the keptn-sandbox for release 0.6.2 and 0.7.0. The tutorials have been updated and point to each of the releases. Full installation has been tested on both.
The `keptn-in-a-box.sh` is already executable, its just when downloading the raw file via curl it will be by default only readable. One could also do a git clone repo and then cd into the directory. We can later discuss the pros/cons of each approach. 

Thanks

**Comment by jetzlstorfer** [comment]
Thanks for clarification!
Didn't know the file permissions get lost when fetching via `curl` but makes sense.
I'll take a final look at then let's get it merged!

**Pull request merged**
