### PR TITLE
adding quality gate tutorial for 0.8

### PR DESCRIPTION
**Pull request by grabnerandi**
Signed-off-by: Andreas Grabner <grabnerandi@gmx.at>

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
Preview: https://deploy-preview-131--keptn-tutorials.netlify.app/tutorials/keptn-quality-gates-dynatrace-08-on-k3s/index.html?index=..%2F..keptn08x#1

**Comment by jetzlstorfer** [comment]
Please remove the brackets, inside codelabs this is not rendered as a standard markdown:
image

**Comment by jetzlstorfer** [comment]
https://deploy-preview-131--keptn-tutorials.netlify.app/tutorials/keptn-quality-gates-dynatrace-08-on-k3s/index.html?index=..%2F..keptn08x#2 

The right bottom corner is a bit misleading as it does not show the date. Any way to update this screenshot? 
image

**Comment by grabnerandi** [comment]
> https://deploy-preview-131--keptn-tutorials.netlify.app/tutorials/keptn-quality-gates-dynatrace-08-on-k3s/index.html?index=..%2F..keptn08x#2
> 
> The right bottom corner is a bit misleading as it does not show the date. Any way to update this screenshot?
> image

This is intentional as we are passing in a build number with the value 1 which then shows up down there. So - it is not expected to see a date there but just the number 1

**Comment by grabnerandi** [comment]
> Please remove the brackets, inside codelabs this is not rendered as a standard markdown:
> image

I made them true check boxes

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Pull request merged**
